### PR TITLE
upgrade to net6

### LINKED ISSUE #130: Update to .NET 6
we're currently using 3.1, which will be out of support at the end of the year: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

Hopefully they didn't break too much, but a migration guide exists: https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-60?view=aspnetcore-6.0&tabs=visual-studio

### PR DESCRIPTION
**Pull request by olohr**
Upgrades the framework to net6, fixes #130

### CODE REVIEW

**Comment by Alfer-Star** [comment]
Ich bekomme aktuell den folgenden Error in Mitgliederverwaltung. War der vorher schon da?

info: MemberManager.Application.People.Queries.GetPeopleWithBasicInfo.GetPeopleWithBasicInfoQuery[0]
      MemberManager Request: GetPeopleWithBasicInfoQuery   MemberManager.Application.People.Queries.GetPeopleWithBasicInfo.GetPeopleWithBasicInfoQuery
fail: MemberManager.Application.People.Queries.GetPeopleWithBasicInfo.GetPeopleWithBasicInfoQuery[0]
      MemberManager Request: Unhandled Exception for Request GetPeopleWithBasicInfoQuery MemberManager.Application.People.Queries.GetPeopleWithBasicInfo.GetPeopleWithBasicInfoQuery
      System.MissingMethodException: Method not found: '!!0 AutoMapper.IMapper.Map(System.Object)'.
         at MemberManager.Application.People.Queries.GetPeopleWithBasicInfo.GetPeopleWithBasicInfoQueryHandler.Handle(GetPeopleWithBasicInfoQuery request, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at MemberManager.Application.People.Queries.GetPeopleWithBasicInfo.GetPeopleWithBasicInfoQueryHandler.Handle(GetPeopleWithBasicInfoQuery request, CancellationToken cancellationToken)
         at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler|0()
         at MemberManager.Application.Common.Behaviours.UnhandledExceptionBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\Users\alfer\Desktop\Dev Projects\MemberManager\src\Application\Common\Behaviours\UnhandledExceptionBehaviour.cs:line 22
fail: MemberManager.WebUI.Filters.ApiExceptionFilter[0]
      Unknown error processing request
      System.MissingMethodException: Method not found: '!!0 AutoMapper.IMapper.Map(System.Object)'.
         at MemberManager.Application.People.Queries.GetPeopleWithBasicInfo.GetPeopleWithBasicInfoQueryHandler.Handle(GetPeopleWithBasicInfoQuery request, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at MemberManager.Application.People.Queries.GetPeopleWithBasicInfo.GetPeopleWithBasicInfoQueryHandler.Handle(GetPeopleWithBasicInfoQuery request, CancellationToken cancellationToken)
         at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler|0()
         at MemberManager.Application.Common.Behaviours.UnhandledExceptionBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\Users\alfer\Desktop\Dev Projects\MemberManager\src\Application\Common\Behaviours\UnhandledExceptionBehaviour.cs:line 22
         at MemberManager.Application.Common.Behaviours.ValidationBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\Users\alfer\Desktop\Dev Projects\MemberManager\src\Application\Common\Behaviours\ValidationBehavior.cs:line 33
         at MemberManager.Application.Common.Behaviours.PerformanceBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\Users\alfer\Desktop\Dev Projects\MemberManager\src\Application\Common\Behaviours\PerformanceBehaviour.cs:line 33
         at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MemberManager.WebUI.Controllers.PeopleController.GetWithBasicInfo() in C:\Users\alfer\Desktop\Dev Projects\MemberManager\src\webui\Controllers\PeopleController.cs:line 29
         at lambda_method965(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1] 
      Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ProblemDetails'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action MemberManager.WebUI.Controllers.PeopleController.GetWithBasicInfo (MemberManager.WebUI) in 23.4327ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'MemberManager.WebUI.Controllers.PeopleController.GetWithBasicInfo (MemberManager.WebUI)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5001/api/People/GetWithBasicInfo - - - 500 - application/problem+json;+charset=utf-8 35.8196ms

**Comment by olohr** [comment]
Hast du dotnet 6.0 installiert? Vielleicht musst du mal alle build Dateien löschen

**Comment by Alfer-Star** [comment]
Dotnet 6 habe ich installiert. Ich probiere mal die Build Dateien zu löschen.

**Comment by olohr** [comment]
Ich hab den gleichen Error bei den Tests, muss das erstmal fixen

**Comment by Alfer-Star** [comment]
Nachdem ich dotnet clean durchgeführt habe. Ist das Problem nicht mehr aufgetreten. 
YAY

**Pull request merged**
